package Interpreter;

public enum Simboli {
    INVALID_CHAR, NO_SYMBOL, OR, AND, NEAR, NOT, WORD, OPEN_PARENTHESIS, CLOSE_PARENTHESIS, STRING, EOF, COMMA,
    CREATE, DELETE, MOVE, MOVE_OFFSET, SCALE, LIST, GROUP, UNGROUP, AREA, PERIMETER, CIRCLE, IMG, NUMBER
}
